version: '3.3'

services:

  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    ports:
     - "80:80"
    environment:
     WORDPRESS_DB_HOST: db:3306
     WORDPRESS_DB_USER: wordpress
     WORDPRESS_DB_PASSWORD: wordpress
     WORDPRESS_TABLE_PREFIX: 'wp_'
     WORDPRESS_DEBUG: 1
    volumes:
    - "./wp-content:/var/www/html/wp-content"

  db:
    image: mysql:5.7
    command: mysqld --sql_mode="" --max_allowed_packet=9999999999999999
    volumes:
      # - "./dump.sql:/docker-entrypoint-initdb.d/dump.sql"
      - ./.dbdata:/var/lib/mysql"
    environment:
     MYSQL_ROOT_PASSWORD: somewordpress
     MYSQL_DATABASE: wordpress
     MYSQL_USER: wordpress
     MYSQL_PASSWORD: wordpress
